apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'test'
  description: 'this is only a test'
  annotations:
    goharbor.io/repository-slug: backstage/busybox
spec:
  type: service
  lifecycle: experimental
  owner: devops